trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any Cpu'

steps:
- displayName: 'Build Solution'
  script: msbuild /t:Publish /p:Configuration=$(BuildConfiguration) /p:$(BuildPlatform) /p:OutDir=$(Build.ArtifactStagingDirectory)
  
