trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any Cpu'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/t:Publish /p:OutDir=$(Build.ArtifactStagingDirectory)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'